### ISSUE TITLE
not showing res button near my corpse after dead

### ISSUE THREAD

**Issue by stephanelol** [WowLegacyCore/HermesProxy#51]
Game ver 1.12 with 1.14 client
not showing res button near my corpse after dead, 
relogin can't fix it.
can res at graveyard or login with 1.12 client.

**Comment by 0blu** [comment]
Can't really reproduce, on which server did you test this on?

**Comment by celguar** [comment]
Also what proxy version? I was under impression it was fixed some time ago

**Comment by stephanelol** [comment]
@celguar 
proxy version: HermesProxy.Windows.27-05-2022
somehow it still happen every time.

**Comment by stephanelol** [comment]
@0blu
server name: NeverEnd WoW
ip address: 47.98.233.3
set realmlist "wow.newow.org"

**Comment by stephanelol** [comment]
the problem happen again with Version 2022-06-01 3.0.1+19

**Comment by Mige5** [comment]
Also experienced this with TBC classic.

**Comment by Energizer188** [comment]
I experienced the same thing on the Everlook PTR
No button to rez near my corpse, only at graveyard

**Comment by Resistofc** [comment]
I have the same problem on Everlook. Can't res at my corpse.

**Comment by Resistofc** [comment]
@ratkosrb thanks that works but playing with helm and cloak shown is a no go for me. Will this get fixed, or is there another workaround?

**Comment by 0blu** [comment]
This issue will be fixed in a new release today.
